### ISSUE TITLE
部署秘钥 显示一直是wait.....

### ISSUE THREAD

**Issue by glily** [alaxli/ansible_ui#12]
直接后台运行 $ansible -i /home/ansible/hosts.txt all  -u ansible -m ping -k
SSH password: 
192.168.163.140 | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
ssh一直连接不上，但是直接ssh ansible@192.168.163.140是成功的，防火墙，selinux也都关闭了，还是不行，请教高手！感激不尽。

**Comment by kenhq03** [comment]
也是部署密钥一直wait，在uwsg的log里面报下面错误
Internal Server Error: /ansible/test/deploykey
Traceback (most recent call last):
  File "/home/ansible/envansible/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "./desktop/apps/ansible/views.py", line 777, in deploykey
    hostlist = get_hosts(inventory, hosts)
  File "./desktop/apps/ansible/tasks.py", line 319, in get_hosts
    inventory = Inventory(hostfile)
TypeError: **init**() takes at least 3 arguments (2 given)
[pid: 223|app: 0|req: 165/165] 192.168.105.9 () {50 vars in 1156 bytes} [Thu Feb 25 18:03:05 2016] POST /ansible/test/deploykey => generated 10998 bytes in 100 msecs (HTTP/1.1 500) 3 headers in 120 bytes (1 switches on core 0)

**Comment by fzsens** [comment]
更换一下ansible的版本到1.9.X

**Comment by dtbdtb** [comment]
my is ansible 2.2.1.0,but same problem 
so ,how deep this problem,can writer give us some hints??

**Comment by weinshun** [comment]
我也是这个问题，求哪位已经解决的说一下。

**Comment by uziomg** [comment]
我也是这个问题，求哪位已经解决的说一下。

**Comment by tjlygdx** [comment]
python-ansible 1.9.6
