### ISSUE TITLE
部署密钥一直提示please wait

### ISSUE THREAD

**Issue by sunyaxiong** [alaxli/ansible_ui#14]
后台debug提示
`Internal Server Error: /ansible/test/deploykey
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ansible/ansible_ui/desktop/apps/ansible/views.py", line 777, in deploykey
    hostlist = get_hosts(inventory, hosts)
  File "/home/ansible/ansible_ui/desktop/apps/ansible/tasks.py", line 319, in get_hosts
    inventory = Inventory(hostfile)
TypeError: __init__() takes at least 3 arguments (2 given)
[14/Apr/2016 17:23:18] "POST /ansible/test/deploykey HTTP/1.1" 500 12966`

这是语法错误吧

**Comment by icode** [comment]
我也是这个问题，郁闷啊

**Comment by phildman** [comment]
我也是，搞不定，好像是django的问题

**Comment by dtbdtb** [comment]
我也是这个问题，请作者能否指点下！！！！

**Comment by weinshun** [comment]
我也是这个问题，请作者帮忙回答一下。

**Comment by uziomg** [comment]
遇到了同样的问题，请问怎么解决啊

**Comment by grayflight** [comment]
安装ansible==1.9.x
