### ISSUE TITLE
初始化数据库报错，寻求帮助

### ISSUE THREAD

**Issue by zhuanglu** [alaxli/ansible_ui#22]
(envansible) [ansible@vm-007-node014 ansible_ui]$ python manage.py schemamigration desktop.apps.account --init
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ansible/envansible/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/ansible/envansible/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ansible/envansible/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/ansible/envansible/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/ansible/envansible/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ansible/envansible/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/home/ansible/envansible/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError kombu.transport.django: No module named django
(envansible) [ansible@vm-007-node014 ansible_ui]$ 

环境：python 2.7.13 django 1.6.0

**Comment by fzsens** [comment]
先执行以下envansible虚拟环境的激活。

**Comment by zhuanglu** [comment]
(envansible) [ansible@vm-007-node016 ~]$ source envansible/bin/activate
么有用呀

**Comment by zhuanglu** [comment]
感谢anzerchen

python 2.7.3
requirements.txt

amqp==1.4.9
ansible==2.2.0.0
anyjson==0.3.3
billiard==3.3.0.23
celery==3.1.25
cffi==1.9.1
cryptography==1.7.1
Django==1.6
django-auth-ldap==1.2.8
django-celery==3.1.16
django-crispy-forms==1.4.0
django-guardian==1.3
django-jsonfield==1.0.1
django-multisite==1.3.1
django-widget-tweaks==1.4.1
enum34==1.1.6
idna==2.2
ipaddress==1.0.17
Jinja2==2.9.4
kombu==3.0.37
MarkupSafe==0.23
meld3==1.0.2
mongoengine==0.9.0
MySQL-python==1.2.5
olefile==0.44
paramiko==2.1.1
pexpect==4.2.1
Pillow==4.0.0
ptyprocess==0.5.1
pyasn1==0.1.9
pycparser==2.17
pycrypto==2.6.1
pymongo==3.4.0
python-ldap==2.4.28
python-magic==0.4.12
pytz==2016.10
PyYAML==3.12
requests==2.12.4
requests-file==1.4.1
simplejson==3.10.0
six==1.10.0
South==1.0.2
supervisor==3.3.1
threadpool==1.3.2
tldextract==2.0.2
uWSGI==2.0.14
vine==1.1.3

**Comment by weinshun** [comment]
用你@zhuanglu提供的require.txt也不行，报错：
  File "/data/soft/app/python2.7/env/lib/python2.7/site-packages/kombu/utils/__init__.py", line 17, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name _uuid_generate_random

**Comment by weinshun** [comment]
请问你的这个问题是如何解决的。

**Comment by sunzxl** [comment]
(envansible) ansible@ubuntu:~/project/ansible_ui$         python manage.py schemamigration desktop.apps.account --init
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ansible/project/envansible/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/ansible/project/envansible/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ansible/project/envansible/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/ansible/project/envansible/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/ansible/project/envansible/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/ansible/project/envansible/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/home/ansible/project/envansible/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError guardian: cannot import name register
这个问题怎么解决？？？
