### ISSUE TITLE
求解答，安装成功后下发任务一直运行状态是pending，求教是什么问题呢？

### ISSUE THREAD

**Issue by shui4321** [alaxli/ansible_ui#23]
安装成功后下发任务一直运行状态是pending，求教是什么问题呢？

**Comment by tjlygdx** [comment]
celery 没有启动

**Comment by handsoncheng** [comment]
你好，我目前搭建好了，但是遇到了一个问题，执行脚本或者其他远程操作都会提示
Traceback (most recent call last):
File "/data/soft/app/python2.7/ansible_ui/ansible_ui/desktop/apps/ansible/tasks.py", line 257, in run
status, stdout, stderr = self.run_pexpect(job_pk, args, cwd, env, passwords)
File "/data/soft/app/python2.7/ansible_ui/ansible_ui/desktop/apps/ansible/tasks.py", line 205, in run_pexpect
child = pexpect.spawn(args[0], args[1:], cwd=cwd, env=env)
File "/data/soft/app/python2.7/env/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 197, in init
self._spawn(command, args, preexec_fn, dimensions)
File "/data/soft/app/python2.7/env/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 270, in _spawn
'executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: /data/soft/app/python2.7/ansible_ui/ansible_ui/playbooks.

这个应该怎么解决啊?状态显示的是error

**Comment by tjlygdx** [comment]
/data/soft/app/python2.7/ansible_ui/ansible_ui/playbooks. 这个应该是setting.py　中配置的playbook的路径

**Comment by dqiang** [comment]
@handsoncheng 你的问题解决了么？
