### ISSUE TITLE
亲测可用的requirements.txt（带版本号）

### ISSUE THREAD

**Issue by gayshub** [alaxli/ansible_ui#24]
Django==1.6
Jinja2==2.8.1
MarkupSafe==1.0
MySQL-python==1.2.5
Pillow==4.0.0
PyYAML==3.12
South==1.0.2
amqp==1.0.13
ansible==2.2.1.0
anyjson==0.3.3
argparse==1.2.1
asn1crypto==0.22.0
celery==3.0.11
cffi==1.9.1
cryptography==1.8.1
django-auth-ldap==1.2.10
django-celery==3.0.11
django-guardian==1.3.2
django-jsonfield==1.0.1
enum34==1.1.6
idna==2.5
ipaddress==1.0.18
kombu==2.5.16
meld3==1.0.2
olefile==0.44
packaging==16.8
paramiko==2.1.2
pexpect==4.2.1
ptyprocess==0.5.1
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
pyparsing==2.2.0
python-dateutil==1.5
python-ldap==2.4.32
python-magic==0.4.12
pytz==2016.10
simplejson==3.10.0
six==1.10.0
supervisor==3.3.1
threadpool==1.3.2
uWSGI==2.0.14
vine==1.1.3
wsgiref==0.1.2

**Comment by gayshub** [comment]
不过这个项目功能有限

**Comment by linsheng9731** [comment]
这个得顶一下!

**Comment by handsoncheng** [comment]
你好，我目前搭建好了，但是遇到了一个问题，执行脚本或者其他远程操作都会提示
Traceback (most recent call last):
  File "/data/soft/app/python2.7/ansible_ui/ansible_ui/desktop/apps/ansible/tasks.py", line 257, in run
    status, stdout, stderr = self.run_pexpect(job_pk, args, cwd, env, passwords)
  File "/data/soft/app/python2.7/ansible_ui/ansible_ui/desktop/apps/ansible/tasks.py", line 205, in run_pexpect
    child = pexpect.spawn(args[0], args[1:], cwd=cwd, env=env)
  File "/data/soft/app/python2.7/env/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 197, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/data/soft/app/python2.7/env/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 270, in _spawn
    'executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: /data/soft/app/python2.7/ansible_ui/ansible_ui/playbooks.

这个应该怎么解决啊

**Comment by xuhuigithub** [comment]
不对 ansible 应该用1.9.6的吧
