### ISSUE TITLE
部署完成后，发布任务，状态显示error

### ISSUE THREAD

**Issue by handsoncheng** [alaxli/ansible_ui#26]
你好，我目前搭建好了，但是遇到了一个问题，执行脚本或者其他远程操作都会提示
Traceback (most recent call last):
File "/data/soft/app/python2.7/ansible_ui/ansible_ui/desktop/apps/ansible/tasks.py", line 257, in run
status, stdout, stderr = self.run_pexpect(job_pk, args, cwd, env, passwords)
File "/data/soft/app/python2.7/ansible_ui/ansible_ui/desktop/apps/ansible/tasks.py", line 205, in run_pexpect
child = pexpect.spawn(args[0], args[1:], cwd=cwd, env=env)
File "/data/soft/app/python2.7/env/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 197, in init
self._spawn(command, args, preexec_fn, dimensions)
File "/data/soft/app/python2.7/env/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 270, in _spawn
'executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: /data/soft/app/python2.7/ansible_ui/ansible_ui/playbooks.

这个应该怎么解决啊?状态显示的是error

**Comment by dqiang** [comment]
作者也不回答下。。。作者已经不做码农了么
