### ISSUE TITLE
部署密钥出现问题

### ISSUE THREAD

**Issue by xuhuigithub** [alaxli/ansible_ui#28]
大家安装后都能正常使用吗？现在部署密钥的时候不成功，一直报输入的参数是3个，只获得了2个。

**Comment by scorpiopio** [comment]
我也遇到了，报错信息如下：
Internal Server Error: /ansible/test/deploykey
Traceback (most recent call last):
  File "/root/envansible/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/ansible_ui/desktop/apps/ansible/views.py", line 777, in deploykey
    hostlist = get_hosts(inventory, hosts)
  File "/root/ansible_ui/desktop/apps/ansible/tasks.py", line 319, in get_hosts
    inventory = Inventory(hostfile)
TypeError: __init__() takes at least 3 arguments (2 given)
[26/Dec/2017 11:23:14] "POST /ansible/test/deploykey HTTP/1.1" 500 12809
