### ISSUE TITLE
ExceptionPexpect: The command was not found or was not executabl

### ISSUE THREAD

**Issue by loveshell** [alaxli/ansible_ui#6]
部署搭建成功，执行任何任务都出现如下错误
```
traceback

                Traceback (most recent call last):
  File "/home/ansible/ansible_ui/desktop/apps/ansible/tasks.py", line 253, in run
    status, stdout, stderr = self.run_pexpect(job_pk, args, cwd, env, passwords)
  File "/home/ansible/ansible_ui/desktop/apps/ansible/tasks.py", line 204, in run_pexpect
    child = pexpect.spawn(args[0], args[1:], cwd=cwd, env=env)
  File "/usr/lib/python2.6/site-packages/pexpect/__init__.py", line 511, in __init__
    self._spawn(command, args)
  File "/usr/lib/python2.6/site-packages/pexpect/__init__.py", line 616, in _spawn
    'executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: /envansible_dir/bin/ansible-playbook.
```

**Comment by loveshell** [comment]
解决了
